# Exercices python du 12/09/2023

### Exercice 1

Écrivez un programme qui demande à l'utilisateur de saisir un nombre entier positif et affiche tous les nombres de 1 jusqu'à ce nombre (inclus).

In [1]:
b = input()
a = int(float(b.replace(",",".")))
if(a <= 0):
    print("N'est pas un nombre positif")
else :
    print("Les nombres sont :")
    for i in range(1,a+1):
        print(i)

Les nombres sont :
1
2


### Exercice 2

Écrivez une fonction qui prend une liste de nombres en entrée et renvoie une nouvelle liste contenant uniquement les nombres positifs.

In [ ]:
def Positif(a):
    for i in range(len(a)):
        if (a[i] > 0):
            print(a[i])
Positif([-1,-2,-3,0,5,6,7,8,9])

5
6
7
8
9


### Exercice 3

Écrivez une fonction qui prend une liste de mots en entrée et renvoie une nouvelle liste contenant les mots dont la première lettre est une voyelle (a, e, i, o, u).

In [ ]:
def Voyelle_en_1er(a):
    j = 0
    voyelles = ("a","e","i","o","u","A","E","I","O","U")
    for i in range(len(a)):
        if (a[i][0] in voyelles):
            j += 1
            print(a[i])
    if j == 0 :
        print("Aucun des mots proposés commencent par une voyelle")
        
Voyelle_en_1er(["Chevre","Aligator","Tortue","e"])

Aligator
e


### Exercice 4

Écrivez une fonction qui prend un nombre entier en entrée et affiche si ce nombre est positif, négatif ou nul.

In [ ]:
def Positif_ou_negatif_ou_nul(a):
    if(a > 0):
        print("Positif")
    elif(a < 0):
        print("Negatif")
    else:
        print("Nul (bouh)")
Positif_ou_negatif_ou_nul(-1)

Negatif


### Exercice 5

Écrivez un programme qui demande à l'utilisateur de saisir un mot et affiche si ce mot contient plus de 5 caractères.

In [ ]:
def Mot_de_plus_de_5_caractères(a):
    if len(a) > 5:
        print("Il y a plus de 5 caractères")
    else :
        print("Il y a moins de 5 caractères")
Mot_de_plus_de_5_caractères(input("Entre un mot : "))
    

Entre un mot : Saucisse
Il y a plus de 5 caractères


### Exercice 6

Écrivez un programme qui demande à l'utilisateur de saisir 5 nombres entiers, acquisition clavier, les stocke dans une liste, puis affiche la liste.

In [ ]:
liste_nombre = []
for i in range(5):
    liste_nombre.append(input("Ajoute le nombre n°" + str(i+1) + " = "))
    
print(liste_nombre)

Ajoute le nombre n°1 = 1
Ajoute le nombre n°2 = 2
Ajoute le nombre n°3 = 3
Ajoute le nombre n°4 = 4
Ajoute le nombre n°5 = 5
['1', '2', '3', '4', '5']


In [ ]:
liste_nombre = [input("Ajoute le nombre n°" + str(i+1) + " = ") for i in range(5)]

print(liste_nombre)

Ajoute le nombre n°1 = 1
Ajoute le nombre n°2 = 2
Ajoute le nombre n°3 = 3
Ajoute le nombre n°4 = 4
Ajoute le nombre n°5 = 5
['1', '2', '3', '4', '5']


### Exercice 7

Écrivez une fonction qui prend une liste de nombres en entrée et renvoie la somme de tous les éléments de la liste.

In [ ]:
def Somme(a):
    b = 0
    for i in range(len(a)):
        b += int(a[i])
    print("La somme est de " + str(b))

Somme([66,66])

La somme est de 132


### Exercice 8

Écrivez une fonction qui prend une liste de mots en entrée et renvoie une nouvelle liste contenant la longueur de chaque mot.

In [ ]:
def longueur_mot(a):
    count_l = []
    for i in range(len(a)):
        count_l.append(len(a[i]))
    print("Voici les différents longueur de mots pour les differents mots proposés : " + str(count_l))
    
longueur_mot(["AAAA","BBBBB","CCC","DD","E"])

Voici les différents longueur de mots pour les differents mots proposés : [4, 5, 3, 2, 1]


### Exercice 9

Écrivez une fonction qui prend une liste de nombres en entrée et renvoie une nouvelle liste contenant uniquement les nombres pairs de la liste initiale.

In [ ]:
def Paire(a):
    j = 0
    for i in range(len(a)):
        if (a[i]%2 == 0):
            j += 1 
            print(a[i])
    if j == 0:
        print("Aucun nombre n'est paire")
    
            
Paire([1,2,3,4,5,6,7,8,9])

2
4
6
8


### Exercice 10

Écrivez un programme qui prend une liste de mots en entrée, acquisition clavier, les trie par ordre alphabétique et affiche la liste triée.

In [ ]:
def Tri(a):
    a.sort()
    print(a)
    
Tri(["HAHAHA","AHAHAHA"])

['AHAHAHA', 'HAHAHA']


### Exercice 11

Écrivez un programme qui demande à l'utilisateur de saisir une phrase et affiche le nombre de caractères de cette phrase (en comptant les espaces).

In [ ]:
def Count_caractère(a):
    print("Cette chaîne de caractères contient : " + str(len(a)) + " caractère(s)")

Count_caractère("Je ne sais pas quoi écrire !")

Cette chaîne de caractères contient : 28 caractère(s)


### Exercice 12

Écrivez une fonction qui prend une chaîne de caractères en entrée et renvoie cette chaîne inversée.

In [ ]:
def Inverse(a):
    b = ""
    for i in range(1, len(a)+1):
        b += a[-i]
    print("Le mot " + str(a) + " donne à l'envers le mot : " + str(b))
        
Inverse("Salut")

Le mot Salut donne à l'envers le mot : tulaS


### Exercice 13

Écrivez une fonction qui prend une chaîne de caractères en entrée et renvoie le nombre de mots dans cette chaîne (un mot est séparé par un espace).

In [ ]:
def Count_mot(a):
    print("La chaîne de caractère contient : " + str(a.count(" ")+1) + " mot(s)")
    
Count_mot("Je ne sais pas quoi écrire !")

La chaîne de caractère contient : 7 mot(s)


### Exercice 14

Écrivez une fonction qui prend une chaîne de caractères en entrée et renvoie une nouvelle chaîne où chaque mot est en majuscules.

In [ ]:
def Majuscule(a):
    print(a.upper())
    
Majuscule("tout doucement")

TOUT DOUCEMENT


### Exercice 15

Écrivez une fonction qui prend une chaîne de caractères en entrée et renvoie True si cette chaîne est un palindrome (c'est-à-dire qu'elle se lit de la même manière de gauche à droite et de droite à gauche), sinon renvoie False.

In [ ]:
def Palindrome(a):
    b = ""
    for i in range(1, len(a)+1):
        b += a[-i]
    if a == b:
        return True
    else:
        return False
Palindrome("kayak")

True

### Exercice 16

Écrivez un programme qui demande à l'utilisateur de deviner un nombre secret (par exemple 42). Le programme indique à l'utilisateur si le nombre à deviner est plus grand ou plus petit que sa proposition et continue de demander un nombre tant que l'utilisateur ne trouve pas le nombre secret. Une fois que l'utilisateur trouve le nombre secret, affichez un message de félicitations.

In [ ]:
import random

def JustePrix():
    num = random.randint(1, 100)
    guess = 0
    while guess != num:
        guess = int(input("Choisis un nombre : "))
        if guess == num:
            print("Felicitation !")
        elif guess > num:
            print("C'est moins")
        else:
            print("C'est plus")

JustePrix()

Choisis un nombre : 50
C'est plus
Choisis un nombre : 75
C'est plus
Choisis un nombre : 88
C'est moins
Choisis un nombre : 80
C'est plus
Choisis un nombre : 84
C'est plus
Choisis un nombre : 86
Felicitation !


### Exercice 17

Écrivez une fonction qui prend un nombre entier en entrée et affiche tous les nombres de 1 jusqu'à ce nombre (inclut) en utilisant une boucle "while".

In [ ]:
def Count_while(a):
    i = 1
    while i != a:
        print(i)
        i += 1
    print(a)

Count_while(15)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Exercice 18

Écrivez une fonction qui prend une liste de nombres en entrée et renvoie une nouvelle liste contenant uniquement les nombres positifs en utilisant une boucle "while".

In [ ]:
def paire_while(a):
    i = 0
    while i != len(a):
        if a[i] % 2 == 0:
            print(a[i])
        i += 1

paire_while([1,2,3,4,5,6,7,8,9])

2
4
6
8


### Exercice 19

Écrivez une fonction qui prend une liste de mots en entrée et renvoie une nouvelle liste contenant les mots dont la première lettre est une voyelle (a, e, i, o, u) en utilisant une boucle "while".

In [ ]:
def Voyelle_en_1er_while(a):
    j = 0
    voyelles = ("a","e","i","o","u","A","E","I","O","U")
    i = 0
    while i != len(a):
        if (a[i][0] in voyelles):
            j += 1
            print(a[i])
        i += 1
    if j == 0 :
        print("Aucun des mots proposés commencent par une voyelle")
        
Voyelle_en_1er_while(["Chevre","Aligator","Tortue","e"])

Aligator
e


### Exercice 20

Écrivez un programme qui demande à l'utilisateur de saisir un mot et affiche si ce mot contient plus de 5 caractères en utilisant une boucle "while". Bah pour faire quoi ?

In [ ]:
def Mot_de_plus_de_5_caractères(a):
    if len(a) > 5:
        print("Il y a plus de 5 caractères")
    else :
        print("Il y a moins de 5 caractères")
Mot_de_plus_de_5_caractères(input("Entre un mot : "))

Entre un mot : Saucisse
Il y a plus de 5 caractères


## BONUS

### Exercice 21

Écrivez une fonction qui prend un nombre entier en entrée et affiche la suite de Fibonacci jusqu'à l'ordre de ce nombre. La suite de Fibonacci est une séquence d'entiers où chaque nombre est la somme des deux nombres précédents. La séquence commence généralement par 0 et 1.

In [ ]:
def Suite_Fibonnaci(a):
    b = []
    for i in range(0,a+1):
        if i == 0 or i == 1:
            b.append(1)
        else:
            c = b[i-2] + b[i-1]
            b.append(c)
    print(b)

Suite_Fibonnaci(5)

[1, 1, 2, 3, 5, 8]


### Exercice 22

calculer 0.1+0.2 avec python expliquer le résultat. Comment obtenir le résultat souhaité dans ce cas ?

In [ ]:
print(0.1 + 0.2)

print(round(0.1 + 0.2,2))

0.30000000000000004
0.3


# Exercice Numpy 12/09/2023

### Exercice 1

Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [ ]:
import numpy as np

a = np.arange(1,11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercice 2

Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [79]:
a = np.random.rand(5)
print(a)

[0.99447353 0.53260439 0.36753201 0.49610434 0.49835665]


### Exercice 3

Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [ ]:
def Somme_numpy(a):
    b = sum(a)
    print(b)

Somme_numpy(np.arange(1,11))

55


### Exercice 4

Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

def produit_scalaire(a, b):
    if len(a) != len(b):
        print("Produit scalaire impossible")
    j = 0
    i = 0
    c = 0
    while j != len(b):
        c += a[i]*b[j]
        i += 1
        j += 1
    
    print(c)

produit_scalaire(a,b)

32


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

def produit_scalaire2(a, b):
    print(np.dot(a,b))

produit_scalaire2(a,b)

32


### Exercice 5

Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [33]:
def Element_unique(a):
    suppr = []
    for i in range(len(a)):
        for j in range(len(a)):
            if i == j:
                continue
            elif (a[i] == a[j]):
                suppr.append(i)
                break
    b = []
    for k in range(len(a)):
        if k in suppr:
            continue
        else : 
            b.append(a[k])
    print(b)

Element_unique(np.array([1,2,3,4,5,6,7,8,9,10,10,10]))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
def Element_unique2(a):
    b = np.unique(a)
    print(b)

Element_unique2(np.array([1,2,3,4,5,6,7,8,9,10,10,10]))

[ 1  2  3  4  5  6  7  8  9 10]


### Exercice 6

Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [38]:
def Croissant(a):
    b = []
    already = []
    for k in range(len(a)):
        min = -1
        j = 0
        for i in range(len(a)):

            if min < 0:
                if i in already:
                   continue 
                else :
                    min = a[i]
                    j = i
            elif min >= a[i]:
                if j == i:
                    continue
                elif i in already:
                   continue 
                else:
                    min = a[i]
                    j = i
        already.append(j)
        b.append(min)
    print(b)

Croissant([9,7,2,4,5,8,1,4])

[1, 2, 4, 4, 5, 7, 8, 9]


In [6]:
import numpy as np

def Croissant2(a):
    
    print(np.sort(a))

a = np.array([9,7,2,4,5,8,1,4])
Croissant2(a)

[1 2 4 4 5 7 8 9]


### Exercice 7

Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [17]:
def moy_med_ecart(a):
    moy = np.mean(a)
    med = np.median(a)
    ecart = np.nanstd(a)
    print(np.var(a) ** (1/2))
    print("la moyenne est de : " + str(moy) + "\nla médiane est : " + str(med) + "\nl'ecart-type est de : " + str(ecart))

moy_med_ecart(np.array([9,7,2,4,5,8,1,4]))

2.6457513110645907
la moyenne est de : 5.0
la médiane est : 4.5
l'ecart-type est de : 2.6457513110645907


### Exercice 8

Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [4]:
import numpy as np

def zero_un(a):
    b = np.empty(len(a),dtype=int)
    for i in range(len(a)):
        if a[i] < 5:
            b[i] = 0
        else:
            b[i] = 1
    print(b)

zero_un(np.array([9.2,7,2,4,5,8,1,4]))

[1 1 0 0 1 1 0 0]


In [16]:
def zero_un2(a):
    b = np.greater_equal(a,5)*1
    print(b)

zero_un2(np.array([1,2,3,4,5,6,7,8,9,10,10,10]))

[0 0 0 0 1 1 1 1 1 1 1 1]


### Exercice 9

Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [78]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 3))
print(a)

[[ 2  2  3]
 [ 3  4  2]
 [ 2  7 10]]
